#
# Created by GuHaijun on 2023/7/13.
#

LIBJSONCPP_MODULE_USER_LOCAL_PATH:=$(LOCAL_PATH)

LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

# LIBJSONCPP_LIB_TYPE := STATIC
ifeq ($(LIBJSONCPP_LIB_TYPE),)
    LIBJSONCPP_LIB_TYPE := SHARED
endif

$(warning LIBJSONCPP_LIB_TYPE: $(LIBJSONCPP_LIB_TYPE))

LIBJSONCPP_LOCAL_STATIC_LIBRARIES :=
LIBJSONCPP_LOCAL_SHARED_LIBRARIES :=

ifeq ($(filter $(modules-get-list), jsoncpp, jsoncpp_static),)
    include $(LOCAL_PATH)/libjsoncpp.mk
endif

LIBJSONCPP_LOCAL_C_INCLUDES := $(LOCAL_C_INCLUDES)
LIBJSONCPP_LOCAL_EXPORT_C_INCLUDES := $(LIBJSONCPP_LOCAL_C_INCLUDES)

LOCAL_PATH:=$(LIBJSONCPP_MODULE_USER_LOCAL_PATH)
